services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=llama-3.1-8b-instant
      - HF_EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=enterprise-rag
    volumes:
      - ./data:/app/data
      - pip-cache:/root/.cache/pip
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pip-cache: